export const ResponseMessage = {
    USER_CREATED: 'User created',
    USER_UPDATED: 'User updated',
    USER_NOT_FOUND: 'User not found',
    USER_ALREADY_EXISTS: 'User already exists',
    USER_UPDATED_SUCCESSFULLY: 'User updated successfully',
    USER_DELETION_SUCCESSFULLY: 'User deleted successfully',
    INTERNAL_SERVER_ERROR: "Internal Server Error",
    REQUIRED_FIELD_MISSING: "Please fill the required field",
    EMAIL_ALREADY_EXISTS: "Email already exists",
    INVALID_CREDENTIALS: "Invalid credentials",
    LOGIN_SUCCESS: "Login successfully",
    TOKEN_NOT_AUTHORIZED: "Token not authorized",
    USER_NOT_AUTHORIZED: "User not authorized",
    BLOG_CREATED: "Blog created successfully",
    BLOGS_FETCHED: "Blogs fetched successfully",
    BLOG_UPDATED: "Blog updated successfully",
    BLOG_NOT_FOUND: "Blog not found",
    BLOG_DELETION_SUCCESSFULLY: "Blog deleted successfully",
    COMMENT_CREATED: "Comment created successfully",
    COMMENTS_FETCHED: "Comments fetched successfully",
    UNAUTHORIZED_ACCESS: "Unauthorized access",
    BLOG_DELETED: "Blogs deleted successfully",
    BLOG_LIKED: "Blogs liked successfully",
    BLOG_UNLIKED: "Blogs unliked successfully",
    COMMENT_ADDED: "Comment added successfully",
    BLOG_ID_REQUIRED: "Blogs ID required"

}